In [1]:
import pandas as pd
pd.set_option("display.width", 120)
pd.set_option("display.max_columns", 30)

titanic = pd.read_csv(r"C:\Users\Daniel\Desktop\Machine learning\Titanic_Cleaned.csv")
print(titanic.shape)
titanic.head()

(775, 9)

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [2]:
df2 = titanic.copy()

# apply + lambda: number -> category
df2["fare_band"] = df2["fare"].apply(lambda x: "20%" if x >= 50 else "10%")

# map + dictionary: text -> short code
sex_map = {"male": "M", "female": "F"}
df2["sex_code"] = df2["sex"].map(sex_map)

df2[["sex", "sex_code", "fare", "fare_band"]].head()

      sex sex_code     fare fare_band
0    male        M   7.2500       10%
1  female        F  71.2833       20%
2  female        F   7.9250       10%
3  female        F  53.1000       20%
4    male        M   8.0500       10%

In [3]:
# assign: a new column derived from an existing one
df2 = df2.assign(fare_plus=df2["fare"] * 1.1)

# replace: relabel values
df2["embarked"] = df2["embarked"].replace("S", "Southampton")

df2[["fare", "fare_plus", "embarked"]].head()

      fare  fare_plus     embarked
0   7.2500    7.97500  Southampton
1  71.2833   78.41163            C
2   7.9250    8.71750  Southampton
3  53.1000   58.41000  Southampton
4   8.0500    8.85500  Southampton

In [4]:
# rename a column
df2 = df2.rename(columns={"fare_plus": "fare_plus_10pct"})

# rename a single index label
df2.head(4).rename(index={0: "row zero"})[["sex", "fare"]]

             sex     fare
row zero    male   7.2500
1         female  71.2833
2         female   7.9250
3         female  53.1000

## Sorting, re-indexing, ranking

In [5]:
df2.sort_values("fare", ascending=False).head(5)

     survived  pclass     sex   age  sibsp  parch      fare     embarked  alone fare_band sex_code  fare_plus_10pct
241         1       1  female  35.0      0      0  512.3292            C   True       20%        F        563.56212
647         1       1    male  35.0      0      0  512.3292            C   True       20%        M        563.56212
595         1       1    male  36.0      0      1  512.3292            C  False       20%        M        563.56212
83          1       1  female  23.0      3      2  263.0000  Southampton  False       20%        F        289.30000
315         1       1  female  24.0      3      2  263.0000  Southampton  False       20%        F        289.30000

In [6]:
df2.sort_values(["pclass", "fare"], ascending=[True, False]).head(6)

     survived  pclass     sex   age  sibsp  parch      fare     embarked  alone fare_band sex_code  fare_plus_10pct
241         1       1  female  35.0      0      0  512.3292            C   True       20%        F        563.56212
595         1       1    male  36.0      0      1  512.3292            C  False       20%        M        563.56212
647         1       1    male  35.0      0      0  512.3292            C   True       20%        M        563.56212
27          0       1    male  19.0      3      2  263.0000  Southampton  False       20%        M        289.30000
83          1       1  female  23.0      3      2  263.0000  Southampton  False       20%        F        289.30000
315         1       1  female  24.0      3      2  263.0000  Southampton  False       20%        F        289.30000

In [8]:
df2.sort_values("age", ascending=False).reset_index(drop=True).head(3)

   survived  pclass   sex   age  sibsp  parch     fare     embarked  alone fare_band sex_code  fare_plus_10pct
0         1       1  male  80.0      0      0  30.0000  Southampton   True       10%        M         33.00000
1         0       3  male  74.0      0      0   7.7750  Southampton   True       10%        M          8.55250
2         0       1  male  71.0      0      0  49.5042            C   True       10%        M         54.45462

In [9]:
df2["fare_rank"] = df2["fare"].rank(ascending=False, method="min")
df2.sort_values("fare_rank").head(5)[["fare", "fare_rank"]]

         fare  fare_rank
241  512.3292        1.0
647  512.3292        1.0
595  512.3292        1.0
315  263.0000        4.0
83   263.0000        4.0

## Column order

In [10]:
df2 = df2[["survived", "pclass", "sex", "sex_code", "age", "fare",
           "fare_plus_10pct", "fare_band", "fare_rank", "embarked", "alone"]]
df2.head()

   survived  pclass     sex sex_code   age     fare  fare_plus_10pct fare_band  fare_rank     embarked  alone
0         0       3    male        M  22.0   7.2500          7.97500       10%      711.0  Southampton  False
1         1       1  female        F  38.0  71.2833         78.41163       20%      103.0            C  False
2         1       3  female        F  26.0   7.9250          8.71750       10%      591.0  Southampton   True
3         1       1  female        F  35.0  53.1000         58.41000       20%      133.0  Southampton  False
4         0       3    male        M  35.0   8.0500          8.85500       10%      565.0  Southampton   True

## Grouping and aggregation

In [11]:
df2.groupby("pclass")[["fare", "age"]].mean()

             fare        age
pclass
1       85.675199  36.921048
2       21.889279  29.791646
3       13.588850  25.651297

In [12]:
df2.groupby("pclass")[["fare", "age"]].agg(["min", "max", "mean"])

       fare                        age
        min       max       mean   min   max       mean
pclass
1       0.0  512.3292  85.675199  0.92  80.0  36.921048
2       0.0   73.5000  21.889279  0.67  70.0  29.791646
3       0.0   69.5500  13.588850  0.42  74.0  25.651297

In [13]:
df2.groupby("pclass").agg(min_fare=("fare", "min"), max_age=("age", "max"))

        min_fare  max_age
pclass
1            0.0     80.0
2            0.0     70.0
3            0.0     74.0

In [14]:
df2.groupby("embarked").agg({"fare": "mean", "age": "max", "survived": "mean"})

                  fare   age  survived
embarked
C            63.710056  71.0  0.580645
Q            14.680964  70.5  0.344828
Southampton  29.011046  80.0  0.373665

## Reshaping: melt / pivot

In [15]:
wide = pd.DataFrame({"country": ["USA", "USA", "India", "India"],
                     "year": [2020, 2021, 2020, 2021],
                     "sales": [100, 120, 90, 110],
                     "profit": [20, 25, 18, 22]})
melted = wide.melt(id_vars=["country", "year"], value_vars=["sales", "profit"],
                   var_name="metric", value_name="value")
melted

  country  year  metric  value
0     USA  2020   sales    100
1     USA  2021   sales    120
2   India  2020   sales     90
3   India  2021   sales    110
4     USA  2020  profit     20
5     USA  2021  profit     25
6   India  2020  profit     18
7   India  2021  profit     22

In [16]:
melted.pivot(index=["country", "year"], columns="metric", values="value")

metric        profit  sales
country year
India   2020      18     90
        2021      22    110
USA     2020      20    100
        2021      25    120

In [17]:
df2.groupby(["pclass", "sex"])["survived"].mean().mul(100).round(1).unstack("sex")

sex     female  male
pclass
1         96.8  36.8
2         91.7  18.5
3         47.2  16.1

## Survival analysis

In [18]:
new_sur = df2[df2["survived"] == 1].copy()
print(new_sur["survived"].size, "survived out of", df2["survived"].size)
print("survival rate =", round(new_sur["survived"].size / df2["survived"].size * 100, 2), "%")

320 survived out of 775
survival rate = 41.29 %

In [19]:
df2.groupby(["sex", "pclass"]).agg({"fare": "mean", "age": "mean"}).round(1)

                fare   age
sex    pclass
female 1       106.5  34.1
       2        22.3  28.3
       3        15.7  23.2
male   1        69.1  39.2
       2        21.6  30.9
       3        12.6  26.8